FROM debian:buster-slim

LABEL maintainer="yang <d12y12@hotmail.com>"

ENV LANG=C.UTF-8
ENV TZ=Asia/Shanghai

RUN set -x \
# replace source list by China local
    && cp /etc/apt/sources.list /etc/apt/sources.list.backup \
    && sed -i 's#http://deb.debian.org#http://mirrors.163.com#g' /etc/apt/sources.list \
# change time to local
    && ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
# install packages
    && apt-get update \
    && apt-get install --no-install-recommends --no-install-suggests -y \
                       fcgiwrap \
                       nginx    \
                       cgit=1.2.1+git2.18.0-1     \
                       dumb-init \
                       python3  \
                       python3-pip \
                       python3-pygments \
                       python3-markdown \
                       python3-docutils \
                       python3-bs4 \
                       python3-requests \ 
# development used, should not in the final packages
    && apt-get install --no-install-recommends --no-install-suggests -y \
                       vim \
                       procps \
                       curl \
    && pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple \ 
# clean up
    && rm -rf /var/lib/apt/lists/* \
# set up cgitrc
    && echo "include=/etc/cgitrc.d/\$HTTP_HOST" > /etc/cgitrc

COPY scripts/bootstrap.sh /etc/bootstrap.sh

RUN chmod a+x /etc/bootstrap.sh 

EXPOSE 8080

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/etc/bootstrap.sh"]
